# docker-compose.yml
services:
  bullpeak:
    build: .
    container_name: bullpeak
    restart: unless-stopped
    environment:
      - PORT=3001
      # optional: tune waktu & timeout
      - SCRAPE_TIMEOUT_MS=60000
    ports:
      - "3001:3001"  # Host_Port:Container_Port
    networks:
      - kikilab

networks:
  kikilab:
    external: true
